version: '3.8'

services:
  steez-app:
    container_name: steez-app
    image: steez-website
    depends_on:
      - steez_postgres
    ports:
      - "8080:8080"
    networks:
      - steez-network
    env_file:
      - .env

  steez_postgres:
    image: postgres:16
    container_name: steez_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - steez-db:/var/lib/postgresql/data
    networks:
      - steez-network

volumes:
  steez-db:

networks:
  steez-network:
    driver: bridge

