spring:
  cache:
    type: redis
    cache-names: redis-cache
  datasource:
    url: jdbc:postgresql://192.168.68.105:5432/steez_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  docker:
    compose:
      enabled: false

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
  data:
    redis:
      host: 192.168.68.105
      port: 6379
      password: ${REDIS_PASSWORD}
